"""
Layer 2: Document Generator Service
Generates 22 specification documents for project factory
"""
import os
import json
from datetime import datetime
from typing import Dict, List, Any


class DocumentGenerator:
    """Generate specification documents for Layer 2 Factory"""
    
    def __init__(self, docs_dir: str):
        self.docs_dir = docs_dir
        self.templates = self._load_templates()
    
    def _load_templates(self) -> Dict[str, str]:
        """Load document templates"""
        return {
            'project_identity': self._project_identity_template(),
            'constitution': self._constitution_template(),
            'requirements': self._requirements_template(),
            'variables': self._variables_template(),
            'functions': self._functions_template(),
            'pipeline': self._pipeline_template(),
            'data_contracts': self._data_contracts_template(),
            'state_machines': self._state_machines_template(),
            'dependency_matrix': self._dependency_matrix_template(),
            'business_rules': self._business_rules_template(),
            'test_cases': self._test_cases_template(),
            'forbidden_rules': self._forbidden_rules_template(),
            'id_tracking': self._id_tracking_template(),
            'object_dictionary': self._object_dictionary_template(),
            'event_dictionary': self._event_dictionary_template(),
            'state_dictionary': self._state_dictionary_template(),
            'pattern_dictionary': self._pattern_dictionary_template(),
            'feature_registry': self._feature_registry_template(),
            'interaction_matrix': self._interaction_matrix_template(),
            'ai_build_guard': self._ai_build_guard_template(),
            'operational_orientation': self._operational_orientation_template(),
        }
    
    def generate_all(self, project_name: str, project_data: Dict[str, Any]) -> List[str]:
        """Generate all 21 specification documents"""
        generated_files = []
        
        # Create docs directory for project
        project_docs_dir = os.path.join(self.docs_dir, project_name)
        os.makedirs(project_docs_dir, exist_ok=True)
        
        # Generate each document
        documents = [
            ('00_PROJECT_IDENTITY', 'project_identity'),
            ('01_CONSTITUTION', 'constitution'),
            ('02_REQUIREMENTS', 'requirements'),
            ('03_VARIABLES', 'variables'),
            ('04_FUNCTIONS', 'functions'),
            ('05_PIPELINE', 'pipeline'),
            ('06_DATA_CONTRACTS', 'data_contracts'),
            ('07_STATE_MACHINES', 'state_machines'),
            ('08_DEPENDENCY_MATRIX', 'dependency_matrix'),
            ('09_BUSINESS_RULES', 'business_rules'),
            ('10_TEST_CASES', 'test_cases'),
            ('11_FORBIDDEN_RULES', 'forbidden_rules'),
            ('12_ID_TRACKING', 'id_tracking'),
            ('13_OBJECT_DICTIONARY', 'object_dictionary'),
            ('14_EVENT_DICTIONARY', 'event_dictionary'),
            ('15_STATE_DICTIONARY', 'state_dictionary'),
            ('16_PATTERN_DICTIONARY', 'pattern_dictionary'),
            ('17_FEATURE_REGISTRY', 'feature_registry'),
            ('18_INTERACTION_MATRIX', 'interaction_matrix'),
            ('19_AI_BUILD_GUARD', 'ai_build_guard'),
            ('20_OPERATIONAL_ORIENTATION', 'operational_orientation'),
        ]
        
        for file_prefix, template_key in documents:
            filename = f"{file_prefix}_{project_name.upper()}.md"
            filepath = os.path.join(project_docs_dir, filename)
            
            content = self._generate_document(template_key, project_name, project_data)
            
            with open(filepath, 'w') as f:
                f.write(content)
            
            generated_files.append(filepath)
        
        return generated_files
    
    def _generate_document(self, template_key: str, project_name: str, data: Dict) -> str:
        """Generate a single document from template"""
        template = self.templates.get(template_key, "# {title}\n\n{content}")
        
        return template.format(
            title=template_key.replace('_', ' ').title(),
            project_name=project_name,
            date=datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S WIB'),
            description=data.get('description', 'No description provided'),
            content=data.get('content', 'Content to be generated by AI')
        )
    
    def compile_final_spec(self, project_name: str) -> str:
        """Compile all documents into FINAL_SPEC.md"""
        project_docs_dir = os.path.join(self.docs_dir, project_name)
        final_spec_path = os.path.join(project_docs_dir, f"FINAL_SPEC_{project_name.upper()}.md")
        
        content = f"""# FINAL SPECIFICATION: {project_name.upper()}

**Generated**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S WIB')}
**Status**: READY_FOR_BUILD

---

## Table of Contents

This specification is compiled from the following documents:

"""
        
        # Add table of contents
        documents = [
            '00_PROJECT_IDENTITY',
            '01_CONSTITUTION',
            '02_REQUIREMENTS',
            '03_VARIABLES',
            '04_FUNCTIONS',
            '05_PIPELINE',
            '06_DATA_CONTRACTS',
            '07_STATE_MACHINES',
            '08_DEPENDENCY_MATRIX',
            '09_BUSINESS_RULES',
            '10_TEST_CASES',
            '11_FORBIDDEN_RULES',
            '12_ID_TRACKING',
            '13_OBJECT_DICTIONARY',
            '14_EVENT_DICTIONARY',
            '15_STATE_DICTIONARY',
            '16_PATTERN_DICTIONARY',
            '17_FEATURE_REGISTRY',
            '18_INTERACTION_MATRIX',
            '19_AI_BUILD_GUARD',
            '20_OPERATIONAL_ORIENTATION',
        ]
        
        for i, doc in enumerate(documents, 1):
            content += f"{i}. [{doc}](./{doc}_{project_name.upper()}.md)\n"
        
        content += f"""
---

## Build Instructions

**IMPORTANT**: This specification is FROZEN. 

Do NOT modify any documents in /docs/ folder during build phase.
All changes must go through approval workflow.

### For AI Builder:

1. Read this entire specification carefully
2. Follow all conventions and patterns defined
3. Generate source code only (no .md modifications)
4. Output to workspace/{project_name}/src/
5. Run all tests before completing
6. Generate build report

---

*This is the Single Source of Truth (SSOT) for the {project_name} project.*
"""
        
        with open(final_spec_path, 'w') as f:
            f.write(content)
        
        return final_spec_path
    
    def generate_build_passport(self, project_name: str, validation_results: Dict) -> str:
        """Generate build passport JSON"""
        project_docs_dir = os.path.join(self.docs_dir, project_name)
        passport_path = os.path.join(project_docs_dir, 'build_passport.json')
        
        passport = {
            'project_name': project_name,
            'generated_at': datetime.utcnow().isoformat(),
            'status': 'READY_FOR_BUILD' if validation_results.get('passed', False) else 'PENDING_VALIDATION',
            'readiness_score': validation_results.get('score', 0),
            'documents_generated': 21,
            'validation': validation_results,
            'freeze_status': 'FROZEN',
            'next_step': 'LAYER_3_BUILD',
            'passport_id': f"PASSPORT-{project_name.upper()}-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
        }
        
        with open(passport_path, 'w') as f:
            json.dump(passport, f, indent=2)
        
        return passport_path
    
    # Template methods (simplified - would be expanded with full templates)
    def _project_identity_template(self) -> str:
        return """# Project Identity: {project_name}

**Generated**: {date}

## Basic Information

- **Project Name**: {project_name}
- **Version**: 1.0.0
- **Stack**: Python + Flask + SQLite
- **Architecture**: 3-Layer (PM OS, Factory, Builder)

## Description

{description}

---
"""
    
    def _constitution_template(self) -> str:
        return """# Constitution: {project_name}

**Generated**: {date}

## Permanent Rules

These rules cannot be changed without approval workflow:

1. Specification is King - All implementations must follow FINAL_SPEC.md
2. Sandbox Boundary - Each project isolated in workspace/{{project_name}}/
3. No Direct Build - AI cannot build without frozen specification
4. Audit Everything - All actions logged to timeline
5. Approval Workflow - Changes require review and approval

## Naming Convention

- Python files: snake_case
- JavaScript files: camelCase
- Database tables: snake_case_plural
- API endpoints: RESTful conventions

## Folder Convention

```
workspace/{{project_name}}/
├── docs/
├── src/
├── tests/
└── artifacts/
```

---
"""
    
    def _requirements_template(self) -> str:
        return """# Requirements: {project_name}

**Generated**: {date}

## Functional Requirements

{content}

## Non-Functional Requirements

- Performance: Response time < 500ms
- Availability: 99.9% uptime
- Security: JWT authentication, RBAC
- Scalability: Support 100+ concurrent projects

---
"""
    
    def _variables_template(self) -> str:
        return """# Variables Dictionary: {project_name}

**Generated**: {date}

## Variable Registry

| ID | Name | Type | Scope | Description |
|----|------|------|-------|-------------|
| VAR-001 | project_id | UUID | Global | Unique project identifier |
| VAR-002 | project_name | String | Global | Human-readable project name |
| VAR-003 | workspace_path | String | Global | Path to project workspace |

{content}

---
"""
    
    def _functions_template(self) -> str:
        return """# Functions Dictionary: {project_name}

**Generated**: {date}

## Function Registry

| ID | Name | Parameters | Returns | Description |
|----|------|------------|---------|-------------|
| FN-001 | create_project | name, description | Project | Create new project |
| FN-002 | get_project | project_id | Project | Get project by ID |
| FN-003 | update_project | project_id, data | Project | Update project |

{content}

---
"""
    
    def _pipeline_template(self) -> str:
        return """# Pipeline Dictionary: {project_name}

**Generated**: {date}

## Stage Registry

| ID | Stage | Input | Output | Description |
|----|-------|-------|--------|-------------|
| STAGE-001 | initialization | ide | folder_structure | Initialize project structure |
| STAGE-002 | analysis | references | analysis_report | Analyze references |
| STAGE-003 | first_spec | analysis | first_concept.md | Generate first concept |
| STAGE-004 | documents | first_concept | 20_artifacts | Generate all artifacts |
| STAGE-005 | validation | artifacts | validation_report | Cross-validate artifacts |
| STAGE-006 | compilation | validated_artifacts | FINAL_SPEC.md | Compile final spec |
| STAGE-007 | freeze | FINAL_SPEC | frozen_spec | Freeze specification |
| STAGE-008 | build | frozen_spec | source_code | Execute AI build |

{content}

---
"""
    
    def _data_contracts_template(self) -> str:
        return """# Data Contracts: {project_name}

**Generated**: {date}

## Data Structure Definitions

{content}

---
"""
    
    def _state_machines_template(self) -> str:
        return """# State Machines: {project_name}

**Generated**: {date}

## State Flow Diagrams

{content}

---
"""
    
    def _dependency_matrix_template(self) -> str:
        return """# Dependency Matrix: {project_name}

**Generated**: {date}

## Component Dependencies

{content}

---
"""
    
    def _business_rules_template(self) -> str:
        return """# Business Rules: {project_name}

**Generated**: {date}

## Rule Registry

{content}

---
"""
    
    def _test_cases_template(self) -> str:
        return """# Test Cases: {project_name}

**Generated**: {date}

## Test Registry

{content}

---
"""
    
    def _forbidden_rules_template(self) -> str:
        return """# Forbidden Rules: {project_name}

**Generated**: {date}

## Constraints

The following are FORBIDDEN:

1. ❌ Modifying .md files in /docs/ during build
2. ❌ Building without frozen specification
3. ❌ Cross-project contamination
4. ❌ Skipping validation steps
5. ❌ Direct terminal access for Git

{content}

---
"""
    
    def _id_tracking_template(self) -> str:
        return """# ID Tracking: {project_name}

**Generated**: {date}

## ID Patterns

- Project ID: UUID v4
- Chat ID: UUID v4
- Message ID: UUID v4
- Memory ID: UUID v4
- Job ID: UUID v4
- Build ID: UUID v4

{content}

---
"""
    
    def _object_dictionary_template(self) -> str:
        return """# Object Dictionary: {project_name}

**Generated**: {date}

## Object Registry

| ID | Object | Properties | Methods | Description |
|----|--------|------------|---------|-------------|
| OBJ-001 | Project | id, name, description | to_dict() | Project entity |

{content}

---
"""
    
    def _event_dictionary_template(self) -> str:
        return """# Event Dictionary: {project_name}

**Generated**: {date}

## Event Registry

| ID | Event | Payload | Trigger | Handler |
|----|-------|---------|---------|---------|
| EVT-001 | project.created | {id, name} | POST /api/projects | Timeline.record() |

{content}

---
"""
    
    def _state_dictionary_template(self) -> str:
        return """# State Dictionary: {project_name}

**Generated**: {date}

## State Registry

| ID | State | Transitions | Guard Conditions |
|----|-------|-------------|------------------|
| STATE-001 | active | → archived, → deleted | status == 'active' |

{content}

---
"""
    
    def _pattern_dictionary_template(self) -> str:
        return """# Pattern Dictionary: {project_name}

**Generated**: {date}

## Pattern Registry

{content}

---
"""
    
    def _feature_registry_template(self) -> str:
        return """# Feature Registry: {project_name}

**Generated**: {date}

## Feature List

| ID | Feature | Priority | Status | Description |
|----|---------|----------|--------|-------------|
| FEAT-001 | Project CRUD | Critical | Implemented | Create, read, update, delete projects |

{content}

---
"""
    
    def _interaction_matrix_template(self) -> str:
        return """# Interaction Matrix: {project_name}

**Generated**: {date}

## Component Interactions

{content}

---
"""
    
    def _ai_build_guard_template(self) -> str:
        return """# AI Build Guard: {project_name}

**Generated**: {date}

## Build Guards

The following guards MUST be enforced during build:

1. ✅ Specification frozen before build starts
2. ✅ Build passport present and valid
3. ✅ Workspace sandbox enforced
4. ✅ No .md file modifications allowed
5. ✅ All tests must pass before commit

## Stop Conditions

AI MUST STOP building if:

- Specification not found
- Build passport missing
- Validation failed
- Test failures detected

{content}

---
"""
    
    def _operational_orientation_template(self) -> str:
        return """# Operational Orientation: {project_name}

**Generated**: {date}

## Operational Guide

This document provides operational guidance for the {project_name} project.

## Deployment

1. Install dependencies: `pip install -r requirements.txt`
2. Configure environment variables
3. Initialize database: `flask db init`
4. Start server: `python app.py`

## Monitoring

- Check logs in /logs/
- Monitor database size
- Track API response times

## Maintenance

- Regular backups of database
- Clean old sessions periodically
- Update dependencies monthly

---
"""
